# Example Docker Compose for Erre2
# Doesn't include frontend

version: "2"

volumes:
  db-data:
  erredue-files:

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "erredue"
      POSTGRES_PASSWORD: "erredue"
      POSTGRES_DB: "erredue"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    restart: always
  backend:
    image: "ghcr.io/lbindustries/erre2.0:latest"
    environment:
      # Change these as needed.
      ROOT_URL: "erre2next.fermitech.info"
      BOT_CHANNEL: "ChannelUsername"
      # Set these to the appropriate Docker secrets
      JWT_KEY_FILENAME: "/run/secrets/erre2_jwt_key"
      BOT_KEY_FILENAME: "/run/secrets/erre2_bot_key"
      # Don't touch these.
      DB_URI: "postgresql://erredue:erredue@db/erredue"
    secrets:
      # Set these to the appropriate Docker secrets
      - "erre2_jwt_key"
      - "erre2_bot_key"
    ports:
      - "8080:80"
    volumes:
      - "erredue-files:/usr/src/app/Files"
    depends_on:
      - db
    restart: always
