name: Build backend image
on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
jobs:
  build:
    name: "Build backend image"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Login to GitHub Containers"
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u LBindustries --password-stdin
      # TODO: Improve this with better tags as soon as I find a decent convention
      - name: "Build the docker container `ghcr.io/lbindustries/erre2.0:latest`"
        run: docker build ./backend --tag ghcr.io/lbindustries/erre2.0:latest
      - name: "Upload the container to GitHub Containers"
        run: docker push ghcr.io/lbindustries/erre2.0:latest
