name: "Release new version"

on:
  # Creation of a new tag starting with v
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: Nemesis-FT/.github/.github/workflows/build-poetry.yml@main
    defaults:
      run:
        working-directory: ./backend

  github:
    uses: Nemesis-FT/.github/.github/workflows/release-poetry-github.yml@main
    defaults:
      run:
        working-directory: ./backend
    needs:
      - build

  ghcrio:
    uses: Nemesis-FT/.github/.github/workflows/buildrelease-docker.yml@main
    defaults:
      run:
        working-directory: ./backend
